// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-TUgBjaX5pnnmOXjhk4OwqBDBlAMQyr8',
    appId: '1:821877797236:web:8b12117e92e1898d287c21',
    messagingSenderId: '821877797236',
    projectId: 'chatapp-2fa6b',
    authDomain: 'chatapp-2fa6b.firebaseapp.com',
    storageBucket: 'chatapp-2fa6b.appspot.com',
    measurementId: 'G-3QJ311GGDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlptkxYswk654VWmP3dBKIGmGBMn8H2ow',
    appId: '1:821877797236:android:921821f3ae246407287c21',
    messagingSenderId: '821877797236',
    projectId: 'chatapp-2fa6b',
    storageBucket: 'chatapp-2fa6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiNS3fjoZZOs6AEvT251pYH1olh__QfjM',
    appId: '1:821877797236:ios:afa7e9e30a4138a3287c21',
    messagingSenderId: '821877797236',
    projectId: 'chatapp-2fa6b',
    storageBucket: 'chatapp-2fa6b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiNS3fjoZZOs6AEvT251pYH1olh__QfjM',
    appId: '1:821877797236:ios:afa7e9e30a4138a3287c21',
    messagingSenderId: '821877797236',
    projectId: 'chatapp-2fa6b',
    storageBucket: 'chatapp-2fa6b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-TUgBjaX5pnnmOXjhk4OwqBDBlAMQyr8',
    appId: '1:821877797236:web:0af3dd07f3c0cc1a287c21',
    messagingSenderId: '821877797236',
    projectId: 'chatapp-2fa6b',
    authDomain: 'chatapp-2fa6b.firebaseapp.com',
    storageBucket: 'chatapp-2fa6b.appspot.com',
    measurementId: 'G-QDXY26Y0S6',
  );
}
